name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install dependencies
        run: |
           gem install cocoapods
           pod install

      - name: Build Archive 
        run: |
          xcodebuild -workspace DemoSwiftUI.xcworkspace \
                     -scheme DemoSwiftUI \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $RUNNER_TEMP/DemoSwiftUI.xcarchive \
                      archive -verbose


      - name: Verify Archive Exists
        run: ls $RUNNER_TEMP/DemoSwiftUI.xcarchive

      - name: Export IPA
        run: |
           xcodebuild -exportArchive \
                     -archivePath $RUNNER_TEMP/DemoSwiftUI.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $RUNNER_TEMP

      - name: Verify IPA Exists
        run: ls $RUNNER_TEMP/*.ipa  # Verify if the IPA file was created

      - name: List files in $RUNNER_TEMP
        run: ls -la $RUNNER_TEMP

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DemoSwiftUI-ipa
          path: $RUNNER_TEMP/DemoSwiftUI.ipa

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
